[pytest]
markers =
    pycrypto: marks tests as applicable with PyCrypto backend
    cryptography: marks tests as applicable with cryptography backend
    backend_compatibility: mark tests as testing compatibility between backends
